src/ToDo.Tests/Services/TaskEndpointTests.cs
src/ToDo.UI/appsettings.json
src/ToDo/Business/TaskListServiceExtensions.cs
src/ToDo/Presentation/SearchViewModel.cs
src/ToDo/Presentation/TaskListViewModel.cs
src/ToDo/Presentation/TaskViewModel.cs

feat: Add basic search VM

---

src/ToDo.UI/lists.json
src/ToDo.UI/tasks.json

lists.json and tasks.json have real json

replaced JSONs with real JSONs

---

src/ToDo.UI/ColorPaletteOverride.xaml
src/ToDo.UI/ToDo.UI.projitems
src/ToDo.UI/Views/Dialogs/AddTaskNote.xaml
src/ToDo.UI/Views/Dialogs/AddTaskNote.xaml.cs
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo.UI/Views/TaskPage.xaml
src/ToDo.UI/Views/WelcomePage.xaml

chore: First bunch of generated XAML into the app

---

src/ToDo.UI/Converters/TaskListIconConverter.cs
src/ToDo.UI/ToDo.UI.projitems
src/ToDo.UI/Views/HomePage.xaml
src/ToDo/Business/TaskList.cs

fix: nav-view item icons

---

src/ToDo.UI/Styles/NavigationBar.xaml
src/ToDo.UI/Views/SettingsPage.xaml

- Feature
Add Settings page generated code

feat: Add Settings page generated code

---

src/ToDo.Droid/ToDo.Droid.csproj
src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.UI/App.xaml
src/ToDo.UI/Views/HomePage.xaml
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo.UI/Views/TaskPage.xaml
src/ToDo.UI/Views/WelcomePage.xaml
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj
src/ToDo.iOS/ToDo.iOS.csproj
src/ToDo.macOS/ToDo.macOS.csproj

- Other: Update generated XAML
Update generated XAML for multiple pages and update themes and toolkit packages

chore: Update generated XAML for multiple pages and update themes and toolkit packages

---

src/ToDo.UI/App.xaml.cs
src/ToDo.UI/Styles/NavigationView.xaml
src/ToDo.UI/Views/Dialogs/AddTaskFlyout.xaml
src/ToDo.UI/Views/Dialogs/ExpirationDateFlyout.xaml
src/ToDo.UI/Views/HomePage.xaml
src/ToDo.UI/Views/SearchPage.xaml
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo.UI/Views/TaskListPage.xaml.cs
src/ToDo/Presentation/SettingsViewModel.cs
src/ToDo/Presentation/TaskListViewModel.cs
src/ToDo/Presentation/TaskViewModel.cs

- Other: Add more generated code
Add more generated code for some pages and flyouts

chore: Add more generated code for some pages and flyouts

---

src/ToDo.UI/Views/SearchPage.xaml
src/ToDo/Presentation/SearchViewModel.cs

Fixes https://github.com/unoplatform/uno.todo/issues/133
Fixes https://github.com/unoplatform/uno.todo/issues/134

fix(search): Fixed search to have results at the right time.

---

src/ToDo.UI/Styles/NavigationView.xaml
src/ToDo.UI/Views/HomePage.xaml
src/ToDo.UI/Views/HomePage.xaml.cs

GitHub Issue (If applicable): #135
- Bugfix
fix: nav-view behaviors

fix: nav-view behaviors

---

src/ToDo.Droid/ToDo.Droid.csproj
src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF.Host/ToDo.Skia.Wpf.Host.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.UI/Controls/AncestralBindingExtension.cs
src/ToDo.UI/Controls/ItemsControlBindingExtension.cs
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj
src/ToDo.iOS/ToDo.iOS.csproj
src/ToDo.macOS/ToDo.macOS.csproj
src/ToDo/Presentation/TaskListViewModel.cs

- Feature
Added a new markup extension that can be used to access the parent ItemsControl data-context from inside of the ItemTemplate.

feat(markup): ItemsControlBinding

---

src/ToDo.Droid/ToDo.Droid.csproj
src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.Tests/ToDo.Tests.csproj
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj
src/ToDo.iOS/ToDo.iOS.csproj
src/ToDo.macOS/ToDo.macOS.csproj
src/ToDo/Business/TaskService.cs
src/ToDo/Presentation/TaskListViewModel.cs
src/ToDo/ToDo.csproj

- Bugfix
Fix completed CheckBox for TaskListPage

fix: Completed CheckBox for TaskListPage

---

src/ToDo.UI/Views/SearchPage.xaml
src/ToDo.UI/Views/TaskControl.xaml
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo/Business/ToDoTask.cs
src/ToDo/Presentation/SearchViewModel.cs
src/ToDo/Presentation/TaskListViewModel.cs

fix: Toggle completed and important task in lists

fix: Toggle completed and important task in lists

---

src/ToDo.UI/Views/TaskControl.xaml

fix: Task Title and Background Page

fix: Task Title and Background Page

---

src/ToDo.UI/App.xaml.cs
src/ToDo.UI/Controls/NavigationViewRequestHandler.cs
src/ToDo.UI/Styles/NavigationView.xaml
src/ToDo.UI/ToDo.UI.projitems
src/ToDo.UI/ToDo.UI.shproj
src/ToDo.UI/Views/HomePage.xaml
src/ToDo.UI/Views/HomePage.xaml.cs
src/ToDo.UI/Views/TaskListPage.xaml

GitHub Issue (If applicable): #182
- Bugfix
NavigationView doesn't take up full width on mobile (or small width layout)
NavigationView Pane goes full width and then navigation is done using the main frame of the app

feat: Full screen navigation for small screens

---

src/ToDo.Wasm/wwwroot/authentication-callback

Fixes https://github.com/unoplatform/uno.todo/issues/158

fix(http404): Fixed a http 404 error on Safari

---

src/ToDo.UI/Views/HomePage.xaml

- Bugfix
Fix crash for HomePage by switching previous v1 resources with v2

fix: Crash for HomePage by switching previous v1 resources with v2

---

src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj
src/ToDo.iOS/ToDo.iOS.csproj
src/ToDo.macOS/ToDo.macOS.csproj

- Bugfix
Update to latest Uno.Material package to fix controls padding issues

fix: Update to latest Uno.Material package to fix controls padding issues

---

README.md
src/ToDo.UI/App.xaml.host.cs
src/ToDo.UI/Extensions/NameValueCollectionExtensions.cs
src/ToDo.UI/ToDo.UI.projitems
src/ToDo.Wasm/ToDo.Wasm.csproj

- Feature : Can trigger the mocked endpoint using the querystring
- Other : small cleanup
Could not switch to mocked endpoint
Can switch to mocked endpoint using querystring ?mock=true

Feature : can switch in or out mock endpoint

---

README.md

- Documentation content changes
Add a synced list of the contributors for README.md

docs: Add a synced list of the contributors for README.md

---

src/ToDo.Droid/ToDo.Droid.csproj
src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj
src/ToDo.iOS/ToDo.iOS.csproj
src/ToDo.macOS/ToDo.macOS.csproj

- Build or CI related changes
Adds support for the [Primary/Secondary]Variant[Light/Dark]Brush

chore: bump material packages

---

src/ToDo.Wasm/ToDo.Wasm.csproj

- Bugfix
Unable to build WASM target with VS 17.3.0 preview 1.0
Error:
2>------ Rebuild All started: Project: ToDo.Wasm, Configuration: Debug Any CPU ------
2>C:\source\github\unoplatform\uno.todo\src\ToDo.Wasm\ToDo.Wasm.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Windows.Compatibility 6.0.0, Microsoft.Windows.Compatibility 5.0.0.
2>Done building project "ToDo.Wasm.csproj" -- FAILED.
Removing the Microsoft.Windows.Compatibility package fixes this issue

fix: Removing duplicate reference

---

src/ToDo.UI/App.xaml.host.cs
src/ToDo.UI/ReactiveClasses.cs
src/ToDo.UI/Views/Dialogs/ExpirationDateFlyout.xaml
src/ToDo.UI/Views/TaskControl.xaml
src/ToDo/Business/Models/ToDoTask.cs
src/ToDo/Business/Models/ToDoTaskExtensions.cs
src/ToDo/Data/DateTimeDataConverter.cs
src/ToDo/Data/Models/DateTimeData.cs
src/ToDo/Data/Models/TaskData.cs
src/ToDo/Presentation/Dialogs/ExpirationDateViewModel.cs
src/ToDo/Presentation/TaskViewModel.cs

feat(dueDate): Add ability to edit the due date

feat(dueDate): Add ability to edit the due date

---

src/ToDo.Mobile/ToDo.Mobile.csproj
src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.UI/Strings/Resources.l12n.xml
src/ToDo.UI/Strings/en/Resources.resw
src/ToDo.UI/Strings/es/Resources.resw
src/ToDo.UI/Strings/fr/Resources.resw
src/ToDo.UI/Views/SearchPage.xaml
src/ToDo.UI/Views/SettingsPage.xaml
src/ToDo.UI/Views/TaskControl.xaml
src/ToDo.UI/Views/TaskListPage.xaml
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj

- Bugfix
Misc UI changes to match the M3 Figma file

fix: Misc UI changes to match the M3 Figma file

---

src/ToDo.UI/Strings/en/Resources.resw
src/ToDo.UI/Strings/es/Resources.resw
src/ToDo.UI/Strings/fr/Resources.resw
src/ToDo.UI/Styles/FeedView.xaml

fix: Integrate Laoding template for FeedView

fix: Integrate Laoding template for FeedView

---

src/ToDo.UI/Views/HomePage.xaml

GitHub Issue (If applicable): #https://github.com/unoplatform/uno.todo/issues/342
- Bugfix

fix: Disabling auto selection of task list by default 

---

src/Directory.Build.props
src/Extensions.props
src/Extensions.winui.props
src/ToDo.Mobile/Android/AndroidManifest.xml
src/ToDo.Mobile/ToDo.Mobile.csproj
src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF.Host/ToDo.Skia.Wpf.Host.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.Tests/ToDo.Tests.csproj
src/ToDo.UI/ReactiveClasses.cs
src/ToDo.Wasm/ToDo.Wasm.csproj
src/ToDo.Windows.Desktop/ToDo.Windows.Desktop.csproj
src/ToDo.Windows.Package/ToDo.Windows.Package.wapproj
src/ToDo.sln
src/ToDo/Presentation/SettingsViewModel.cs
src/ToDo/ToDo.csproj

GitHub Issue (If applicable): #163
- Bugfix
Clicking Signout from settings flyout doesn't work
Signout works.

fix: Resolving issue with sign out not working from settings flyout

---

src/ToDo.Skia.Gtk/ToDo.Skia.Gtk.csproj
src/ToDo.Skia.WPF/ToDo.Skia.WPF.csproj
src/ToDo.UI/App.xaml.cs

Fixes for Skia GTK and WPF
